apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-converter-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: currency-converter
  template:
    metadata:
      labels:
        app: currency-converter
    spec:
      containers:
      - name: currency-converter
        # Use the image you pushed to your registry
        image: thunderboi2023/currency-converter:v1
        ports:
        - containerPort: 3000

